function [detectionErrorFloat, detectionErrorNoFloat] = calculatePerformance()
% Function that calls the algorithmPerformance function to find the
% detection performance for each data set. 
% We take FLOAT and NO_FLOAT data separately, to study the performance for
% the two conditions. 

    detectionErrorFloat = [algorithmPerformance('DetectedHealthyGaitEvents/*S1_FLOAT*', 'HealthyGaitEvents/*S1_FLOAT*'),...
        algorithmPerformance('DetectedHealthyGaitEvents/*S2_FLOAT*', 'HealthyGaitEvents/*S2_FLOAT*'), ...
        algorithmPerformance('DetectedHealthyGaitEvents/*S3_FLOAT*', 'HealthyGaitEvents/*S3_FLOAT*'), ...
        algorithmPerformance('DetectedHealthyGaitEvents/*S4_FLOAT*', 'HealthyGaitEvents/*S4_FLOAT*'), ...
        algorithmPerformance('DetectedHealthyGaitEvents/*S5_FLOAT*', 'HealthyGaitEvents/*S5_FLOAT*'), ...
        algorithmPerformance('DetectedHealthyGaitEvents/*S6_FLOAT*', 'HealthyGaitEvents/*S6_FLOAT*')];
    detectionErrorNoFloat = [algorithmPerformance('DetectedHealthyGaitEvents/*S1_NO_FLOAT*', 'HealthyGaitEvents/*S1_NO_FLOAT*'), ...
        algorithmPerformance('DetectedHealthyGaitEvents/*S2_NO_FLOAT*', 'HealthyGaitEvents/*S2_NO_FLOAT*'), ...
        algorithmPerformance('DetectedHealthyGaitEvents/*S3_NO_FLOAT*', 'HealthyGaitEvents/*S3_NO_FLOAT*'), ...
        algorithmPerformance('DetectedHealthyGaitEvents/*S4_NO_FLOAT*', 'HealthyGaitEvents/*S4_NO_FLOAT*'), ...
        algorithmPerformance('DetectedHealthyGaitEvents/*S5_NO_FLOAT*', 'HealthyGaitEvents/*S5_NO_FLOAT*'), ...
        algorithmPerformance('DetectedHealthyGaitEvents/*S6_NO_FLOAT*', 'HealthyGaitEvents/*S6_NO_FLOAT*')];

end