function GroundTruthEMGAlice(leftFoot)

[GaitCyclesFloat1,GaitCyclesNoFloat1] = ...
HealthySubjectSegmentation('Healthy Recordings/Subject1_2019/FLOAT/S1_FLOAT.mat', ...
'Healthy Recordings/Subject1_2019/NO_FLOAT/S1_NO_FLOAT.mat',...
'HealthyGaitEvents/2019_S1_FLOAT.mat', 'HealthyGaitEvents/2019_S1_NO_FLOAT.mat',leftFoot);

GroundTruthToolEMGLaure(GaitCyclesFloat1,'/GroundTruthBurstsRight/2019_S1_FLOAT.mat');
GroundTruthToolEMGLaure(GaitCyclesNoFloat1,'/GroundTruthBurstsRight/201_S1_NO_FLOAT.mat');

[GaitCyclesFloat2, GaitCyclesNoFloat2] = ...
    HealthySubjectSegmentation('Healthy Recordings/Subject2_2019/FLOAT/S2_FLOAT.mat', ...
    'Healthy Recordings/Subject2_2019/NO_FLOAT/S2_NO_FLOAT.mat', ...
    'HealthyGaitEvents/2018_S2_FLOAT.mat', 'HealthyGaitEvents/2019_S2_NO_FLOAT.mat',leftFoot);

GroundTruthToolEMGLaure(GaitCyclesFloat2,'/GroundTruthBurstsRight/2019_S2_FLOAT.mat');
GroundTruthToolEMGLaure(GaitCyclesNoFloat2,'/GroundTruthBurstsRight/2019_S2_NO_FLOAT.mat');

[GaitCyclesFloat3,GaitCyclesNoFloat3] = ...
    HealthySubjectSegmentation('Healthy Recordings/Subject3_2019/FLOAT/S3_FLOAT.mat', ...
    'Healthy Recordings/Subject3_2019/NO_FLOAT/S3_NO_FLOAT.mat', ...
    'HealthyGaitEvents/2018_S3_FLOAT.mat', 'HealthyGaitEvents/2019_S3_NO_FLOAT.mat', leftFoot);

GroundTruthToolEMGLaure(GaitCyclesFloat3,'/GroundTruthBurstsRight/2019_S3_FLOAT.mat');
GroundTruthToolEMGLaure(GaitCyclesNoFloat3,'/GroundTruthBurstsRight/2019_S3_NO_FLOAT.mat');

% [GaitCyclesSCIFloat,GaitCyclesSCINoFloat] = ...
%     HealthySubjectSegmentation('Healthy Recordings/Subject4_2018/FLOAT/S4_FLOAT.mat', ...
%     'Healthy Recordings/Subject4_2018/NO_FLOAT/S4_NO_FLOAT.mat', ...
%     'HealthyGaitEvents/2018_S4_FLOAT.mat', 'HealthyGaitEvents/2018_S4_NO_FLOAT.mat',leftFoot);
% 
% GroundTruthToolEMGLaure(GaitCyclesFloat4,'/GroundTruthBurstsRight/2018_S4_FLOAT.mat');
% GroundTruthToolEMGLaure(GaitCyclesNoFloat4,'/GroundTruthBurstsRight/2018_S4_NO_FLOAT.mat');
% 
% [GaitCyclesFloat5,GaitCyclesNoFloat5] = ...
%     HealthySubjectSegmentation('Healthy Recordings/Subject5_2018/FLOAT/S5_FLOAT.mat', ...
%     'Healthy Recordings/Subject5_2018/NO_FLOAT/S5_NO_FLOAT.mat',...
%     'HealthyGaitEvents/2018_S5_FLOAT.mat', 'HealthyGaitEvents/2018_S5_NO_FLOAT.mat',leftFoot);
% 
% GroundTruthToolEMGLaure(GaitCyclesFloat5,'/GroundTruthBurstsRight/2018_S5_FLOAT.mat');
% GroundTruthToolEMGLaure(GaitCyclesNoFloat5,'/GroundTruthBurstsRight/2018_S5_NO_FLOAT.mat');
% 
% [GaitCyclesFloat6,GaitCyclesNoFloat6] = ...
%     HealthySubjectSegmentation('Healthy Recordings/Subject6_2018/FLOAT/S6_FLOAT.mat', ...
%     'Healthy Recordings/Subject6_2018/NO_FLOAT/S6_NO_FLOAT.mat',...
%     'HealthyGaitEvents/2018_S6_FLOAT.mat', 'HealthyGaitEvents/2018_S6_NO_FLOAT.mat',leftFoot); 
% 
% GroundTruthToolEMGLaure(GaitCyclesFloat6,'/GroundTruthBurstsRight/2018_S6_FLOAT.mat');
% GroundTruthToolEMGLaure(GaitCyclesNoFloat6,'/GroundTruthBurstsRight/2018_S6_NO_FLOAT.mat');
    

end